### ISSUE TITLE
Server->Client chain in client type not scope safe

### ISSUE THREAD

**Issue by saysjonathan** [luxflux/puppet-openvpn#111]
If you use openvpn::client & openvpn::server in different classes, Openvpn::Client is unable to create a relationship because it is attempting to chain two top-level resources.

    err: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find resource 'Openvpn::Server[vpn.foo.net]' for relationship on 'Openvpn::Client[user]' on node vpn.foo.net

Chaining types within a defined type is probably a poor idea since you can't make assumptions about the scoping. Removing the chain from the define works fine but it's ultimately up to the user to ensure they create the server prior to creating the client.

**Comment by luxflux** [comment]
What do you suggest to do? I never saw such an error before. Could you show me some example puppet code so I can reproduce this?

**Comment by luxflux** [comment]
Closed because of inactivity.
