### ISSUE TITLE
Wrong port on clients

### ISSUE THREAD

**Issue by Fale** [luxflux/puppet-openvpn#113]
If the port is changed with:

  openvpn::server { 'name':
    port         => '443',
  }

it will be used for the server but not for the clients, so the config of the clients will have to be manually fixed before it works

**Comment by luxflux** [comment]
The client definition takes a [port argument](https://github.com/luxflux/puppet-openvpn/blob/master/manifests/client.pp#L45-L48), with this you can define it with puppet and don't have to fix it manually.

You could even specify a default:

```puppet
Openvpn::Client {
  port  => 1337,
  proto => 'udp'
}

openvpn::server {
  port  => 1337,
  proto => 'udp',
  # stuff
}

openvpn::client {
  # stuff
}
openvpn::client {
  # stuff
}
openvpn::client {
  # stuff
}
```
