### ISSUE TITLE
Execution fails if perl is not installed

### ISSUE THREAD

**Issue by Bhuwan** [luxflux/puppet-openvpn#114]
Happens to be that I do not have perl installed on the machine I am using and execution fails because of this:

https://github.com/luxflux/puppet-openvpn/blob/master/manifests/client.pp#L224

I'm thinking of some suggested fixes.

**Comment by luxflux** [comment]
Did you find a solution?

**Comment by Bhuwan** [comment]
@luxflux I installed perl before hand :).  Not a "solution" but a workaround.

**Comment by luxflux** [comment]
Okay... :smile: As this is an edge case (I think I never saw a system without Perl :smile:), I will just close the issue at this point.
