### ISSUE TITLE
Support RHEL 7

### ISSUE THREAD

**Issue by tarjei** [luxflux/puppet-openvpn#120]
Changes needed:

* The service description must check for systemd and use openvpn.$servername as servicename.
* RHEL7 does not have the openvpn-ldap-auth package

**Comment by luxflux** [comment]
Thanks for the listing. Disabling installing of the `openvpn-ldap-auth` package is already fixed in master.

#98 is a start to handle the systemd part.

**Comment by tarjei** [comment]
Great! thanks a bundle!
