### ISSUE TITLE
Unable to identify debian wheezy 

### ISSUE THREAD

**Issue by x-drum** [luxflux/puppet-openvpn#123]
When using a small (reduced) debian wheezy installation, openvpn::server is unable to identify it
via openvpn::params.

This is due the lack of the lsb-release package (in a minimal/reduced installation the dependency chain for lsb-release can be huge):
Without the lsb package installed $::lsbdistid and $::lsbdistrelease facts are empty and eval will fail with the message: `Not supported OS / Distribution: Debian`

**Comment by luxflux** [comment]
Which facts do you suggest to use instead of `$::lsbdistid` and `$::lsbdistrelease`? Which ones are available?

**Comment by x-drum** [comment]
A combination of $::operatingsystem and $::operatingsystemrelease would be possible in that situation,
for example:
[..]
'Debian': { # Debian/Ubuntu
      case $::operatingsystem {
        'Debian': {
          # Version > 8.0.0, jessie
          if(versioncmp($operatingsystemrelease, '8.0') >= 0) {
[..]

**Comment by luxflux** [comment]
I added this now in a branch called `amazon-wheezy-small-support` and opened a pull request #134. Could you test it?

**Comment by peterbeck** [comment]
by the way: shouldn't it be "8.0" instead of "8.0.0" in the Debian Jessie section ?
```
if(versioncmp($::lsbdistrelease, '8.0') >= 0) {
```
I had to change to 8.0 as there is no 8.0.x available yet and then puppet used the Wheezy section...

**Comment by luxflux** [comment]
Thanks @peterbeck, I updated the branch. Do you mind checking it again?

**Comment by peterbeck** [comment]
Hi @luxflux - just tried the branch and it seems to work as expected. Thanks !

**Comment by luxflux** [comment]
Thanks for testing @peterbeck, I need to resolve #44 first before merging.
