### ISSUE TITLE
Option conflict in client mode

### ISSUE THREAD

**Issue by gingaz** [luxflux/puppet-openvpn#143]
Hi,

my client server gets unconfigured out of the box. The problem seems to be the conflict of settings. Currently the script adds "client" (which is a shorthand of "tls-client") and "tls-server".
The problem seems to lie in server.pp fragment [1]. If I want a default-setting client  with tcp I will inevitably get settings conflict.

I am thinking if this code block should be moved under conditional statement block that tackles server-specific values to line 447, before "if !$shared_ca {".

````Server.pp
    if $tls_server {
      $real_tls_server = $tls_server
    } else {
    $real_tls_server = $proto ? {
        /tcp/   => true,
        default => false
      }
    }
````

Cheers,
Gin

**Comment by gingaz** [comment]
To remedy this, I have modified server.erb in the following way:

````
<% if @remote == '' -%> #@remote instead of @proto. If it is not a client (remote=''), then it is a server
proto <%= @proto %>-server
<% else -%>
proto <%= @proto %>
<% end -%>
````

I think I haven't made any other changes. Will update in case it is not true.

**Comment by luxflux** [comment]
Thanks, @gingaz. What's the state now?

**Comment by justicel** [comment]
I'll get you a pull request to fix this an a couple other things.

**Comment by peterbeck** [comment]
somehow i get this error now (Debian Wheezy):

```Could not retrieve catalog from remote server: Error 400 on SERVER:
Syntax error at '{'; expected '}' at /etc/puppet/modules/openvpn/manifests/server.pp:438```

**Comment by justicel** [comment]
Which puppet version do you have? That's an in-line comment there which should be properly terminated with about any version I've tried before.

**Comment by peterbeck** [comment]
it's the default debian puppet version:
```dpkg -l |grep puppet```
```ii  puppet                             2.7.23-1~deb7u3```

it seems to work when commenting the code block (it's a server acting as client configuration)

**Comment by luxflux** [comment]
@justicel moved the comment. Could you try the current master version? If it does not work, could you replace the the `unless $tls_client {` with `if !$tls_client {` ?

**Comment by luxflux** [comment]
I just tried the tests with puppet 2.7 and they were failing. I did the change I mentioned in my last comment and they are passing. So looks like it's fixed.
