### ISSUE TITLE
Module compatible with existing PKI infrastructure?

### ISSUE THREAD

**Issue by chihoko** [luxflux/puppet-openvpn#149]
Is it possible to use this module with an existing PKI with deployed server certificates?

**Comment by luxflux** [comment]
Theoretically, this should work as long as you manually build up a directory structure this module expects. It should not overwrite any files (expect `vars` for which you have to set the variables when using `openvpn::server`).

Better try it on a testing machine first :smile:

If you find a way, I'd be happy if you could explain it to me? So we can create a documentation for this.

**Comment by luxflux** [comment]
Closed due to inactivity.
