### ISSUE TITLE
2.9.0 tag?

### ISSUE THREAD

**Issue by rvalle** [luxflux/puppet-openvpn#173]
Hi!
I am about to start coding a little path when I noticed that I could not checkout the latest tag.
maybe it needs to be pushed?
will start working on 2.8.0
R.

**Comment by luxflux** [comment]
Aw, yeah... missed to push it... Did it now, thanks for the heads-up.

**Comment by rvalle** [comment]
no problem, I will merge my patch... and send a PR.
