### ISSUE TITLE
Added support for inline tls-auth in ovpn config files

### ISSUE THREAD

**Issue by jkroepke** [luxflux/puppet-openvpn#175]
Hi,

I have enable tls-auth on my openvpn server. I would be nice, if the tls-auth key can be included to the ovpn file.

It is required, if i want to enable ovpn on my mobile phone.

Check: https://community.openvpn.net/openvpn/wiki/IOSinline

**Comment by Philio** [comment]
I found this change broke client generation when tls-auth is disabled:

    Debug: /Stage[main]/Vpn/Openvpn::Client[<client_name>]/Concat::Fragment[/etc/openvpn/<server_name>/download-configs/<client_name>.ovpn/tls_auth_open_tag]/File[/opt/puppetlabs/puppet/cache/concat/_etc_openvpn_<server_name>_download-configs_<client_name>.ovpn/fragments/11__etc_openvpn_<server_name>_download-configs_<client_name>.ovpn_tls_auth_open_tag]: Nothing to manage: no ensure and the resource doesn't exist
    Error: /Stage[main]/Vpn/Openvpn::Client[<client_name>]/Concat::Fragment[/etc/openvpn/<server_name>/download-configs/<client_name>.ovpn/tls_auth]/File[/opt/puppetlabs/puppet/cache/concat/_etc_openvpn_<server_name>_download-configs_<client_name>.ovpn/fragments/12__etc_openvpn_<server_name>_download-configs_<client_name>.ovpn_tls_auth]: Could not evaluate: Could not retrieve information from environment production source(s) file:/etc/openvpn/<server_name>/download-configs/<client_name>/keys/<client_name>/ta.key
    Debug: Concat::Fragment[/etc/openvpn/<server_name>/download-configs/<client_name>.ovpn/tls_auth]: Resource is being skipped, unscheduling all events
    Debug: /Stage[main]/Vpn/Openvpn::Client[<client_name>]/Concat::Fragment[/etc/openvpn/<server_name>/download-configs/<client_name>.ovpn/tls_auth_close_tag]/File[/opt/puppetlabs/puppet/cache/concat/_etc_openvpn_<server_name>_download-configs_<client_name>.ovpn/fragments/13__etc_openvpn_<server_name>_download-configs_<client_name>.ovpn_tls_auth_close_tag]: Nothing to manage: no ensure and the resource doesn't exist

**Comment by jkroepke** [comment]
Hi, 

I add a pull request for this. No Idea how add to the pull request to the old pull request

**Comment by luxflux** [comment]
Thank you for reporting. Has been fixed with #179.

**Comment by jkroepke** [comment]
Hi!

do you know, when you release an update on puppet forge?

**Comment by luxflux** [comment]
Haha, just preparing a release in this moment. :smile:
