### ISSUE TITLE
Supporting port-share

### ISSUE THREAD

**Issue by choene** [luxflux/puppet-openvpn#182]
With openvpn, you can run a web server on the same port as openvpn.
I wrote a small extension to support this feature.

**Comment by choene** [comment]
diff --git a/manifests/server.pp b/manifests/server.pp
index 24a7048..940284d 100644
--- a/manifests/server.pp
+++ b/manifests/server.pp
@@ -74,6 +74,10 @@
 #   Integer.  The port the openvpn server service is running on
 #   Default: 1194
 #
+# [*portshare*]
+#   String.  The address and port to which non openvpn request shall be forwared, e.g. 127.0.0.1 8443
+#   Default: undef
+#
 # [*proto*]
 #   String.  What IP protocol is being used.
 #   Default: tcp
@@ -376,6 +380,7 @@ define openvpn::server(
   $local                     = $::ipaddress_eth0,
   $logfile                   = false,
   $port                      = '1194',
+  $portshare                 = undef,
   $proto                     = 'tcp',
   $status_version            = '',
   $status_log                = "/var/log/openvpn/${name}-status.log",
diff --git a/templates/server.erb b/templates/server.erb
index 715570d..5769606 100644
--- a/templates/server.erb
+++ b/templates/server.erb
@@ -31,6 +31,9 @@ proto <%= @proto %>
 nobind
 <% else -%>
 port <%= @port %>
+<% if @portshare -%>
+port-share <%= @portshare %>
+<% end -%>
 <% end -%>
 <% if @real_tls_server -%>
 tls-server

**Comment by choene** [comment]
[patch.txt](https://github.com/luxflux/puppet-openvpn/files/46733/patch.txt)

**Comment by luxflux** [comment]
Thank you for your work. I opened a PR for your patch: #185.
