### ISSUE TITLE
PuppetCA: specifying ca, cert, & key directives

### ISSUE THREAD

**Issue by kierr** [luxflux/puppet-openvpn#183]
First, thank you luxflux and all contributors for this wonderful module!

I'm trying to configure an openvpn server using puppet CA as per: https://community.openvpn.net/openvpn/wiki/PuppetCA

How do I specify ca, cert, and key directives? I have tried without hiera and with, but I can't get the config generating correctly.

    has no parameter named 'ca'
    has no parameter named 'cert'
    has no parameter named 'key'

**Comment by luxflux** [comment]
This will be fixed with #181.
