### ISSUE TITLE
Could not find resource 'Class[Openvpn::Install]' for relationship

### ISSUE THREAD

**Issue by Skalarache** [luxflux/puppet-openvpn#188]
Hello,

I Have an error when I try to deploy Openvpn::server on Debian 8.3 with your code 3.0. (It was OK in my test server Debian 8.1 and your code 2.9)

My puppet conf : 

```puppet
openvpn::server { 'admin_openvpn_server':
                country      => 'FR',
                province     => 'FR',
                city         => 'France',
                organization => 'xxxxxxxxx',
                email        => 'xxxxxxxxx',
                server       => '10.0.0.1 255.255.255.0',
        }
```

And when I try to deploy :

```
root@openvpn:~$ puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find resource 'Class[Openvpn::Install]' for relationship on 'Openvpn::Server[admin_openvpn_server]' on node openvpn.xxxxxxxx.fr
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

In puppet log, i found :

```
Jan 28 10:55:44 puppet puppet-master[30539]: (Scope(Openvpn::Server[admin_openvpn_server])) Could not look up qualified variable '::openvpn::params::pam_module_path'; class ::openvpn::params has not been evaluated
Jan 28 10:55:44 puppet puppet-master[30539]: (Scope(Openvpn::Server[admin_openvpn_server])) Could not look up qualified variable 'openvpn::params::group'; class openvpn::params has not been evaluated
Jan 28 10:55:44 puppet puppet-master[30539]: (Scope(Openvpn::Server[admin_openvpn_server])) Could not look up qualified variable '::openvpn::params::systemd'; class ::openvpn::params has not been evaluated
Jan 28 10:55:45 puppet puppet-master[30539]: (Scope(Openvpn::Ca[admin_openvpn_server])) Could not look up qualified variable 'openvpn::params::group'; class openvpn::params has not been evaluated
Jan 28 10:55:45 puppet puppet-master[30539]: (Scope(Openvpn::Ca[admin_openvpn_server])) Could not look up qualified variable 'openvpn::params::easyrsa_source'; class openvpn::params has not been evaluated
Jan 28 10:55:45 puppet puppet-master[30539]: (Scope(Openvpn::Ca[admin_openvpn_server])) Could not look up qualified variable 'openvpn::params::link_openssl_cnf'; class openvpn::params has not been evaluated
Jan 28 10:55:45 puppet puppet-master[30539]: Could not find resource 'Class[Openvpn::Install]' for relationship on 'Openvpn::Server[admin_openvpn_server]' on node openvpn.xxxxxx.fr
Jan 28 10:55:45 puppet puppet-master[30539]: Could not find resource 'Class[Openvpn::Install]' for relationship on 'Openvpn::Server[admin_openvpn_server]' on node openvpn.xxxxxx.fr
Jan 28 10:55:45 puppet puppet-master[30539]: Could not find resource 'Class[Openvpn::Install]' for relationship on 'Openvpn::Server[admin_openvpn_server]' on node openvpn.xxxxxx.fr
```

Any idea please ?

Regards,

**Comment by luxflux** [comment]
Which puppet versions are you using? Is it the same even though you switch from Debian 8.1 to Debian 8.3?

I did a major release (3.0.0) because it breaks compatibility with Puppet 2.7 (see #164).

**Comment by Skalarache** [comment]
Puppet version is 3.7.2 (master and client). On my test platform (debian 8.1), i was also in 3.7.2 version.

**Comment by luxflux** [comment]
According to the log, this looks like it does not load the class `openvpn`. The changes to this class from 2.9.0 to 3.0.0 are about adding hiera lookups: https://github.com/luxflux/puppet-openvpn/compare/2.9.0...3.0.0#diff-60ae41fd0a31977447947f59940ee9a4R74

Do you use hiera? Is your hiera setup okay? Also, are all the dependencies in [metadata.json](https://github.com/luxflux/puppet-openvpn/blob/3.0.0/metadata.json#L20-L21) satisfied?

**Comment by Skalarache** [comment]
Dependencies are OK, I checked this before opening the issue.

I don't use Hiera. I just make a ".pp" file with : 

node 'openvpn.admin.xxxxxxxxx.fr' inherits default {
        openvpn::server { 'admin_openvpn_server':
                country      => 'FR',
                province     => 'FR',
                city         => 'France',
                organization => 'xxxxxxxx',
                email        => 'xxxxxxxxxx',
                server       => '10.0.0.0 255.255.255.0',
        }
}

**Comment by luxflux** [comment]
What happens if you remove the `hiera_hash` lines in https://github.com/luxflux/puppet-openvpn/compare/2.9.0...3.0.0#diff-60ae41fd0a31977447947f59940ee9a4R74? Does it work?

**Comment by Skalarache** [comment]
Hello,

I tried to comment in manifests/init.pp : 

class openvpn(
  $autostart_all = true,
  $manage_service = true,
#  $client_defaults = hiera_hash('openvpn::client_defaults', {}),
#  $clients = hiera_hash('openvpn::clients', {}),
#  $client_specific_config_defaults = hiera_hash('openvpn::client_specific_config_defaults', {}),
#  $client_specific_configs = hiera_hash('openvpn::client_specific_configs', {}),
#  $revoke_defaults = hiera_hash('openvpn::revoke_defaults', {}),
#  $revokes = hiera_hash('openvpn::revokes', {}),
#  $server_defaults = hiera_hash('openvpn::server_defaults', {}),
#  $servers = hiera_hash('openvpn::servers', {}),
) {

#  validate_hash($client_defaults)
#  validate_hash($clients)
#  validate_hash($client_specific_config_defaults)
#  validate_hash($client_specific_configs)
#  validate_hash($revoke_defaults)
#  validate_hash($revokes)
#  validate_hash($server_defaults)
#  validate_hash($servers)

  class { 'openvpn::params': } ->
  class { 'openvpn::install': } ->
  class { 'openvpn::config': } ->
  Class['openvpn']


But the result is the same : 

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find resource 'Class[Openvpn::Install]' for relationship on 'Openvpn::Server[admin_openvpn_server]' on node xxxxxxx

**Comment by luxflux** [comment]
@Skalarache did you get this fixed? At the moment I am quite out of ideas what could go wrong...

**Comment by luxflux** [comment]
Closed due inactivity.
