### ISSUE TITLE
Error while evaluating a Function Call, cannot currently create client configs when corresponding openvpn::server is extca_enabled

### ISSUE THREAD

**Issue by jkroepke** [luxflux/puppet-openvpn#199]
Hi

after upgrading the openvpn module, puppet runs into an error

```
puppet agent -t 
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, cannot currently create client configs when corresponding openvpn::server is extca_enabled at /etc/puppetlabs/code/environments/production/modules/openvpn/manifests/client.pp:224:23 at /etc/puppetlabs/code/environments/production/site/profile/manifests/openvpn/server.pp:48 on node hostname
```

```
puppet --version
4.5.0
```

I do not defined the param extca_enabled on my resources. Settings extca_enabled to false will throw the error, too.

**Comment by tohuwabohu** [comment]
Same here - any idea how to fix this or at least work around the problem?

**Comment by jkroepke** [comment]
Maybe #201

**Comment by tohuwabohu** [comment]
Yep, using the changes proposed in #201 forks for me.

**Comment by cjeanneret** [comment]
Hello,

I'm hitting that very same problem, with a simple "puppet apply". It seems the code trying to get the ```extca_enabled``` value is just broken. The patch proposed in #201 is more a workaround imho.
The following code just fails:
```Puppet
  ::openvpn::server {'foo':
    city          => 'StarCity',
    country       => 'DC',
    email         => 'admin@foo.bar',
    organization  => 'foo',
    province      => 'VD',
    server        => "${network} ${netmask}",
  }

  ::openvpn::client {'some-user':
    server => 'foo',
  }
```

Cheers,

C.

**Comment by cjeanneret** [comment]
Ah, one more information: using puppet 4.5.2 — might explain, as your tests don't seem to cover 4.x versions?

**Comment by jurgenweber** [comment]
I get it using 3.8.6

**Comment by jkroepke** [comment]
getparam is broken. because getparam return an empty string, if the parameter is false. 
See: https://tickets.puppetlabs.com/browse/MODULES-2874

**Comment by luxflux** [comment]
Thank you all for your investigation!

I merged #201 as a workaround as long as https://tickets.puppetlabs.com/browse/MODULES-2874 has not been fixed.

**Comment by jkroepke** [comment]
Thanks alot!

Since many peoples are affected, you can publish a new version to forge?

**Comment by luxflux** [comment]
Yeah, on it.
