### ISSUE TITLE
How do I change mode from TCP to UDP?

### ISSUE THREAD

**Issue by crudalex** [luxflux/puppet-openvpn#204]
Likewise, how to I change other settings of this module? Where can I find a more detailed documentation? 

Thanks.

**Comment by downspot** [comment]
If you are using hiera, which is much easier to deal with, just add the following as examples:

openvpn::servers:
    proto: 'udp'

openvpn::client_defaults:
    proto: 'udp'

**Comment by luxflux** [comment]
The available parameters of the classes/defines is documented in the files:
* [client.pp](https://github.com/luxflux/puppet-openvpn/blob/master/manifests/client.pp#L49-L52)
* [server.pp](https://github.com/luxflux/puppet-openvpn/blob/master/manifests/server.pp#L86-L89)

Closing this, if you have more questions, just reopen.
