### ISSUE TITLE
$extca_enabled

### ISSUE THREAD

**Issue by unixmind** [luxflux/puppet-openvpn#210]
On branch "master" in client.pp

even if $extca_enabled is not set anywhere (default value : false in ser.pp), Puppet breaks at "cannot currently create client configs when corresponding openvpn::server is extca_enabled"

 $extca_enabled = getparam(Openvpn::Server[$server], 'extca_enabled')
  if $extca_enabled { fail('cannot currently create client configs when corresponding openvpn::server is extca_enabled') }

puppet 4.6.0
puppetserver 2.5.0-1
puppetlabs-stdlib 4.12.0

**Comment by NoodlesNZ** [comment]
I'm also seeing this. It looks like getparam() is returning an empty string instead of a boolean. I'm not sure the reason, but in later puppet versions an empty string is evaluated to `true`.

**Comment by unixmind** [comment]
Hi,
don't worry, this issue has been fixed by Puppet agent 1.6.2-1 !
