### ISSUE TITLE
Download config has incorrect protocol

### ISSUE THREAD

**Issue by adenau** [luxflux/puppet-openvpn#219]
In my puppet manifests, the configuration is

proto => 'udp',

If I look at the configuration file of my server :

proto udp

However, if I look at client config in download-configs :

proto tcp

**Comment by luxflux** [comment]
You also have to define `proto => 'udp'` in your client config: [check client.pp](https://github.com/luxflux/puppet-openvpn/blob/master/manifests/client.pp#L49-L52).
